// Package state implements the "State Manager" component of the
// Orchestration Engine (Architecture Doc Section 3.1). The MVP uses a
// single-instance SQLite store (Section 5.1 - HA support is out of scope
// for v1, TR-13).
package state

import (
	"context"
	"time"
)

// Phase represents where a migration job currently sits in its lifecycle.
// Matches the "SYNCING, SWAPPING, COMPLETED" examples in Architecture Doc
// Section 3.1.
type Phase string

const (
	PhasePreflight      Phase = "PREFLIGHT"
	PhasePreparation    Phase = "PREPARATION"
	PhaseSyncing        Phase = "SYNCING"
	PhaseDeltaSync      Phase = "DELTA_SYNC"
	PhaseValidating     Phase = "VALIDATING"
	PhaseSwapping       Phase = "SWAPPING"
	PhaseRollbackWindow Phase = "ROLLBACK_WINDOW" // FR-08a: post-swap rollback window
	PhaseCleanup        Phase = "CLEANUP"
	PhaseCompleted      Phase = "COMPLETED"
	PhaseFailed         Phase = "FAILED"
	PhaseAborted        Phase = "ABORTED"
)

// Job represents the checkpoint record of a single migration.
// The Reaper (internal/reaper) scans for FAILED/ABORTED jobs, or
// IN_PROGRESS jobs whose last update is older than N minutes, through this
// struct.
type Job struct {
	ID                  string
	SchemaName          string
	TableName           string
	Strategy            string // strategy.Strategy value, kept as string to avoid a circular import
	Phase               Phase
	ReplicationSlotName string // populated in the shadow-table flow, critical for the reaper
	ShadowTableName     string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	RollbackDeadline    *time.Time // FR-08a: after this time, "rollback" is treated as a new migration
	LastError           string

	// Name/Description are optional, purely human-facing labels the
	// caller can attach at creation time (e.g. "Q3 billing schema
	// update" / "Adds the discount_code column ahead of the promo
	// launch"). Neither is ever read by any flow, strategy decision, or
	// rollback logic — they exist solely so the Migration Detail screen
	// has something better than a bare table name to show for "what was
	// this migration about". Both stay empty for jobs created before this
	// field existed, or when the caller simply doesn't provide them.
	Name        string
	Description string

	// The fields below carry the operation details needed by internal/ddlflow
	// and internal/shadowflow to resume a job from its checkpoint (the
	// primitive/string counterparts of strategy.Operation/ColumnChange;
	// again kept as string/primitive types here to avoid a circular import).
	Operation         string // e.g. "ADD_COLUMN", "ALTER_COLUMN_TYPE" (see internal/strategy.Operation)
	ColumnName        string
	ColumnType        string // new column type for ADD_COLUMN, target type for ALTER_COLUMN_TYPE
	DefaultValue      string // empty means "no default"
	IsVolatileDefault bool   // true triggers the Expand & Backfill flow (see Architecture Doc 4.0)

	// DeprecatedColumnName is used ONLY by internal/ddlflow's DROP_COLUMN
	// two-phase flow: once set, it holds the temporary name the original
	// column was renamed to during the "soft drop" (see
	// DDLFlow.executeDropColumn). Empty for every other operation.
	DeprecatedColumnName string

	// IndexName is used by ADD_INDEX/DROP_INDEX — the name of the index
	// being created or dropped.
	IndexName string
	// IndexDefinition is used ONLY by DROP_INDEX: the exact
	// pg_get_indexdef() output captured immediately BEFORE the index is
	// dropped, so Rollback can recreate an identical index later. See
	// DDLFlow.executeDropIndex's doc comment for why this makes dropping
	// an index safely reversible at any time, unlike DROP_COLUMN.
	IndexDefinition string

	// ConstraintName is used by SET_NOT_NULL/ADD_CONSTRAINT — the name of
	// the CHECK constraint used during the "expand and validate" pattern
	// (see strategy.OpSetNotNull's doc comment). For SET_NOT_NULL this may
	// be auto-generated by DDLFlow if the caller left it empty.
	ConstraintName string
	// CheckExpression is used ONLY by ADD_CONSTRAINT: the raw CHECK(...)
	// expression body (e.g. "price > 0"). SET_NOT_NULL never sets this —
	// its check is always "<column> IS NOT NULL" internally.
	CheckExpression string

	// NewColumnName is used ONLY by RENAME_COLUMN: ColumnName holds the
	// existing (old) name, NewColumnName holds the name it's being
	// renamed to. Known at job-creation time (always caller-supplied, no
	// auto-generation like DeprecatedColumnName), so — unlike that field —
	// there is no corresponding Store.Update* setter for it.
	NewColumnName string

	// EstimatedRowCount is the table's estimated row count at the moment
	// the job was created (copied from the strategy.TableStats already
	// fetched to decide the strategy — see orchestrator.StartMigration).
	// It's a snapshot, not re-queried live, so it can drift from the
	// table's actual current size on a long-running migration; that's an
	// accepted trade-off for not needing an extra DB round-trip just for
	// display purposes.
	EstimatedRowCount int64
	// RowsProcessed is a running counter of rows touched by a batched
	// backfill (see internal/ddlflow's backfillLoop and
	// renameBackfillLoop), incremented after each batch via
	// Store.IncrementRowsProcessed. Stays 0 for operations that don't
	// backfill row-by-row (e.g. ADD_INDEX, SET_NOT_NULL) — those apply via
	// a single statement PostgreSQL executes atomically, so there's no
	// meaningful intermediate "rows so far" to report.
	RowsProcessed int64

	// ImpactPeakQueryDurationSeconds is the highest "how long has an
	// active query on this table been running" reading ever observed
	// during this migration — written continuously (write-through, not
	// just at the end) while someone has the opt-in impact-measurement
	// checkbox on (see internal/api's attachImpactMeasurement and
	// impactTracker) while the migration is still running, so it
	// survives regardless of exact timing around the migration
	// finishing. nil means impact measurement was never turned on for
	// this migration — not "measured and found to be zero" — these are
	// deliberately distinguished (see progress.Report's own field for
	// the same reasoning) so the Migration Detail page can tell "nobody
	// checked" apart from "checked, and it was genuinely quiet".
	ImpactPeakQueryDurationSeconds *float64
}

// Store is the interface for persisting checkpoint records.
type Store interface {
	Create(ctx context.Context, job *Job) error
	UpdatePhase(ctx context.Context, jobID string, phase Phase) error
	// UpdatePhaseWithError also persists LastError for jobs transitioning to
	// FAILED (used by internal/ddlflow, internal/shadowflow).
	UpdatePhaseWithError(ctx context.Context, jobID string, phase Phase, lastError string) error
	// UpdateResources persists the replication slot and shadow table names
	// once internal/shadowflow generates them during Preparation — so
	// internal/reaper can find and clean them up by name even if the
	// process crashes before the job reaches a terminal phase.
	UpdateResources(ctx context.Context, jobID string, slotName, shadowTableName string) error
	// UpdateRollbackDeadline persists the FR-08a rollback window deadline
	// once a swap succeeds (see internal/shadowflow.ShadowFlow.Execute).
	UpdateRollbackDeadline(ctx context.Context, jobID string, deadline time.Time) error
	// UpdateImpactPeak persists the current running peak from
	// internal/api's impactTracker — see Job.ImpactPeakQueryDurationSeconds's
	// own doc comment for why this is write-through (called on every
	// poll while measurement is on, not just once at the end).
	UpdateImpactPeak(ctx context.Context, jobID string, peakSeconds float64) error
	// UpdateDeprecatedColumnName persists the temporary name a column was
	// renamed to during DDLFlow's DROP_COLUMN "soft drop" step — see
	// Job.DeprecatedColumnName's doc comment.
	UpdateDeprecatedColumnName(ctx context.Context, jobID string, deprecatedName string) error
	// UpdateIndexName persists the index name for ADD_INDEX/DROP_INDEX jobs.
	UpdateIndexName(ctx context.Context, jobID string, indexName string) error
	// UpdateIndexDefinition persists the pg_get_indexdef() output captured
	// before a DROP_INDEX job's index is dropped — see
	// Job.IndexDefinition's doc comment.
	UpdateIndexDefinition(ctx context.Context, jobID string, definition string) error
	// UpdateConstraintName persists the constraint name for a SET_NOT_NULL
	// job once DDLFlow has resolved it (auto-generating one if the caller
	// left it empty) — see Job.ConstraintName's doc comment. ADD_CONSTRAINT
	// jobs always know their constraint name from creation (it's a
	// required, caller-supplied value), so they never need to call this.
	UpdateConstraintName(ctx context.Context, jobID string, constraintName string) error
	// IncrementRowsProcessed adds delta to the job's running RowsProcessed
	// counter — called after each backfill batch (see
	// internal/ddlflow.backfillLoop/renameBackfillLoop) rather than
	// overwritten wholesale, since the caller only knows how many rows
	// THIS batch touched, not the running total.
	IncrementRowsProcessed(ctx context.Context, jobID string, delta int64) error
	Get(ctx context.Context, jobID string) (*Job, error)
	// ListStale is used by the reaper to detect orphaned resources
	// (Architecture Doc Section 3.3 "Orphan Resource Reaper").
	ListStale(ctx context.Context, olderThan time.Duration) ([]*Job, error)
	// ListAll returns every job, most recently created first — used by the
	// `pgarchimigrator list` CLI command so a user can find a job's exact ID
	// instead of reconstructing it from scrollback or database object
	// names (e.g. a shadow table's inherited index name), which is
	// error-prone and can lead to acting on the wrong job entirely.
	ListAll(ctx context.Context) ([]*Job, error)
	// ListExpiredRollbackWindows returns jobs currently in
	// ROLLBACK_WINDOW whose RollbackDeadline has passed — used by
	// internal/reaper to complete the Cleanup step (Architecture Doc
	// Section 4.1 step 7) for migrations that succeeded but were never
	// explicitly rolled back within their FR-08a grace period. This is
	// deliberately a different signal than ListStale: it represents a
	// SUCCESSFUL migration whose window simply closed, not an orphaned or
	// crashed one.
	ListExpiredRollbackWindows(ctx context.Context) ([]*Job, error)
}
