// Package ecosystem implements pgArchiMigrator's side of the Archi
// ecosystem integration contracts defined in AC-PF-003 (Domain
// Boundaries, Product Manifest and Integration Contracts) — Common
// Event Envelope v1 specifically. See docs/ecosystem/ARCHITECTURE.md
// for the full design rationale.
//
// This package is deliberately isolated from every other internal
// package except internal/state (read-only, for Job field access) and
// internal/entitlement (to decide event granularity) — engines/postgresql/ddlflow
// and engines/postgresql/shadowflow have ZERO awareness this package exists. See
// Store's own doc comment for how events actually get published without
// either of those packages needing a single new line of code.
package ecosystem

import (
	"encoding/json"
	"time"
)

// EnvelopeSpecVersion is the Common Event Envelope schema version this
// package implements — see AC-PF-003 Section 11.1's own `specVersion`
// field.
const EnvelopeSpecVersion = "1.0"

// ProductID is this product's immutable ecosystem identifier — used as
// both Envelope.Producer.ProductID and the product-name segment of
// every EventType this package emits (see EventType's own doc comment
// for the naming convention). Matches the productId this project's
// Product Manifest (see archi-product-manifest.yaml at the repo root)
// registers under.
const ProductID = "pgarchimigrator"

// Envelope is the Common Event Envelope v1 — see AC-PF-003 Section 11.1
// for the canonical shape this mirrors field-for-field. Every event
// pgArchiMigrator publishes to the Archi ecosystem uses this envelope,
// regardless of what triggered it (a migration's own phase transitions
// today; future capabilities — PostgreSQL upgrade, dev/test data
// provisioning — reuse the exact same envelope, only Data/DataSchema/
// EventType change).
type Envelope struct {
	SpecVersion string `json:"specVersion"`
	// EventID is generated by this producer and must be globally
	// unique — see NewEventID. Consumers use it for deduplication (see
	// AC-PF-003 Section 11.2: "Consumer eventId ile duplicate event'leri
	// tolere eder").
	EventID string `json:"eventId"`
	// EventType is immutable per AC-PF-003 Section 11.2 and follows the
	// <product>.<domain>.<past-tense-event>.v<major> convention from
	// Section 11.3 — see this package's EventType constants (defined in
	// ids.go, alongside the EventType string type itself).
	EventType EventType `json:"eventType"`
	// Source identifies the emitting instance — see NewSource.
	Source string `json:"source"`
	// Subject is a short human/log-friendly pointer to what this event
	// is about — "<resourceType>/<resourceId>", not a substitute for
	// ResourceRef (consumers must use ResourceRef for actual
	// correlation; Subject is not guaranteed parseable).
	Subject string `json:"subject"`
	// OccurredAt is when the domain fact actually happened; PublishedAt
	// is when this envelope was constructed for transport — AC-PF-003
	// Section 11.2 draws this distinction explicitly and this package
	// preserves it rather than collapsing both into one timestamp.
	OccurredAt  time.Time `json:"occurredAt"`
	PublishedAt time.Time `json:"publishedAt"`
	// OrganizationID/WorkspaceID are required for tenant-bound events
	// (AC-PF-003 Section 11.2) — empty for Community/self-hosted
	// instances with no ArchiConsole tenant context configured; a
	// future Cloud deployment topology populates these from its own
	// tenant resolution, which this package does not need to know
	// about (see internal/entitlement's own doc comment on Cloud not
	// being a separate code path).
	OrganizationID string `json:"organizationId,omitempty"`
	WorkspaceID    string `json:"workspaceId,omitempty"`
	// CorrelationID/CausationID/LifecycleID are propagated from the
	// triggering command when pgArchiMigrator was invoked BY the
	// ecosystem (see AC-PF-003 Section 12) — empty when a migration was
	// started directly via this product's own CLI/API/dashboard,
	// outside any ArchiConsole-initiated journey. A job started
	// standalone still publishes events; it just correlates to nothing
	// upstream.
	CorrelationID string      `json:"correlationId,omitempty"`
	CausationID   string      `json:"causationId,omitempty"`
	LifecycleID   string      `json:"lifecycleId,omitempty"`
	Producer      Producer    `json:"producer"`
	ResourceRef   ResourceRef `json:"resourceRef"`
	DataSchema    string      `json:"dataSchema,omitempty"`
	// Data is intentionally json.RawMessage, not a concrete struct —
	// this package's event PAYLOADS (what actually goes in Data) are
	// this product's own domain concern and evolve independently of the
	// envelope shape itself; see migration_events.go for the concrete
	// payload types this package currently populates Data with.
	Data  json.RawMessage `json:"data"`
	Trace *Trace          `json:"trace,omitempty"`
}

// Producer identifies which product, and which version of it, emitted
// an event — AC-PF-003 Section 11.1.
type Producer struct {
	ProductID      string `json:"productId"`
	ProductVersion string `json:"productVersion"`
}

// ResourceRef is AC-PF-003 Section 9's Canonical Resource Reference,
// scoped down to the fields an event envelope actually carries (the
// full Resource Reference also has DisplayName/ExternalRefs, which
// belong on the resource's OWN canonical representation, not repeated
// on every event about it).
type ResourceRef struct {
	SourceProduct   string `json:"sourceProduct"`
	ResourceType    string `json:"resourceType"`
	ResourceID      string `json:"resourceId"`
	ResourceVersion string `json:"resourceVersion,omitempty"`
}

// Trace carries W3C-style trace context — AC-PF-003 Section 11.1 lists
// this as part of the envelope but doesn't mandate populating it; this
// package leaves Trace nil until this product has its own tracing
// instrumentation to source real values from (fabricating a traceId
// with no matching span data anywhere would be worse than omitting
// Trace entirely).
type Trace struct {
	TraceID string `json:"traceId,omitempty"`
	SpanID  string `json:"spanId,omitempty"`
}

// ResourceTypeMigrationJob is this product's one resource type — a
// migration job. Follows AC-PF-003 Section 7.1's capability-vocabulary
// dotted convention even though this is a resource type, not a
// capability ID, for the same reasoning: lowercase, product-name-free,
// hierarchical. See archi-product-manifest.yaml's own resourceTypes
// entry, which this constant matches — this package and the manifest
// must never drift apart on this value, so both this package and the
// manifest deliberately reference the SAME idea, if not (today) the
// exact same source: a future improvement could generate the manifest's
// resourceTypes section from this constant instead of maintaining both
// by hand.
const ResourceTypeMigrationJob = "migration.postgresql.job"

// ResourceTypeUpgradeJob is engines/postgresql/upgrade's own resource type — a
// distinct resource from ResourceTypeMigrationJob above, matching that
// package's own "separate Job, not shoehorned into state.Job" design
// (see engines/postgresql/upgrade's package doc comment). Also matches
// archi-product-manifest.yaml's own resourceTypes entry for the
// migration.postgresql.database.upgrade capability — same "both must
// reference the same idea" caution as ResourceTypeMigrationJob's own
// doc comment already notes.
const ResourceTypeUpgradeJob = "migration.postgresql.upgrade-job"
